# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Zero"
license = "MIT"
licenselink = "https://github.com/sunwei/zero/blob/master/LICENSE"
description = "Hugo Theme for sunewi.xyz"
homepage = "https://sunwei.xyz/"
demosite = "https://sunwei.xyz"
tags = ["zero", "sunwei.xyz"]
features = ["clean"]
min_version = "0.41.0"

[author]
  name = "Sun Wei"
  homepage = "https://sunwei.xyz"
